### ISSUE TITLE
Syntax highlighting breaks on multiline

### ISSUE THREAD

**Issue by tscpp** [tscpp/xit-vscode#2]
![image](https://user-images.githubusercontent.com/47453366/161395993-23860c12-a4d3-4423-ae6a-c42c1efe12fb.png)

**Comment by semiherdogan** [comment]
hi,
here is my vscode screenshot

![image](https://user-images.githubusercontent.com/5646041/162723898-d642a60d-3493-4a79-b092-e54e60acba35.png)

"open" and "ongoing" works fine but "checked" syntax highlight is broken.
